services:
  - type: web
    name: berlin-events-finder
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm ci --production=false
      npm run build:prod
    startCommand: |
      cd frontend
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: starter 